### ISSUE TITLE
Fatal error with only Fabric API and Traverse loaded

### ISSUE THREAD

**Issue by apceros1** [TerraformersMC/Terrestria#203]
[12:14:01] [main/INFO]: Loading for game Minecraft 1.16.3
[12:14:03] [main/INFO]: [FabricLoader] Loading 53 mods: fabric-renderer-api-v1@0.3.3+a4467d2a95, fabric-keybindings-v0@0.2.0+3fa9f7c595, terrestria@2.1.2+build.24, fabricloader@0.10.6+build.214, fabric-structure-api-v1@1.1.0+f8ac1db295, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.9.2+a89534ab95, fabric-game-rule-api-v1@1.0.3+a4467d2a95, fabric-api-base@0.2.0+9f0fb4b895, terraform-config-api-v1@1.0.0+build.1, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db295, terraform-surfaces-api-v1@1.0.0+build.1, fabric-textures-v0@1.0.5+a4467d2a95, fabric-rendering-fluids-v1@0.1.12+f8ac1db295, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, traverse@3.0.0+build.6, fabric-renderer-registries-v1@2.2.0+f8ac1db295, terraform-wood-api-v1@1.0.0+build.1, fabric-loot-tables-v1@1.0.1+432ea18895, fabric@0.25.0+build.415-1.16, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-networking-v0@0.1.10+e00ecb5f95, terraform-biome-builder-api-v1@1.0.0+build.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, minecraft@1.16.3, fabric-screen-handler-api-v1@1.1.0+8724984195, fabric-command-api-v1@1.0.9+a4467d2a95, fabric-tool-attribute-api-v1@1.2.4+2b46237995, fabric-renderer-indigo@0.4.3+a4467d2a95, terraform-tree-api-v1@1.0.0+build.1, fabric-item-api-v1@1.2.0+f8ac1db295, fabric-events-interaction-v0@0.4.1+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-rendering-v0@1.1.1+f8ac1db295, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-v1@1.3.1+f8ac1db295, terraform-overworld-biome-extensions-api-v1@1.0.0+build.1, terraform-legacy-v0@0.1.1-SNAPSHOT, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-biome-api-v1@3.0.0+8367596d95, fabric-commands-v0@0.2.0+52d3083695, fabric-registry-sync-v0@0.6.1+a4467d2a95, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, libstructure@1.5, fabric-models-v0@0.1.1+f8ac1db295, fabric-item-groups-v0@0.2.1+a4467d2a95, fabric-object-builders-v0@0.7.1+a4467d2a95, terraform-overworld-biome-extensions-v1@0.1.1-SNAPSHOT, terraform-shapes-api-v1@0.1.0-SNAPSHOT
[12:14:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Primary/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[12:14:15] [main/WARN]: @Redirect conflict. Skipping mixins.terraform-tree-api-v1.json:MixinTreeFeature->@Redirect::terrestria$allowSandyTreeGeneration(Lnet/minecraft/class_3746;Lnet/minecraft/class_2338;)Z with priority 1000, already redirected by mixins.terrestria.json:MixinTreeFeature->@Redirect::terrestria$allowSandyTreeGeneration(Lnet/minecraft/class_3746;Lnet/minecraft/class_2338;)Z with priority 1000
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_5464.<clinit>(class_5464.java:92)
	at net.minecraft.class_5458.method_30571(class_5458.java:46)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector terrestria$allowSandyTreeGeneration(Lnet/minecraft/class_3746;Lnet/minecraft/class_2338;)Z in mixins.terraform-tree-api-v1.json:MixinTreeFeature failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap terraform-tree-api-v1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 21 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (109 ms)
[Version:1.12.2-forge1.12.2-14.23.5.2814] Resolving...
[Version:1.12.2-forge1.12.2-14.23.5.2814] Inherits from 1.12.2
[Version:1.12.2-forge1.12.2-14.23.5.2814] Resolving...
[Version:1.12.2-forge1.12.2-14.23.5.2814] Inherits from 1.12.2
[Version:1.12.2-forge1.12.2-14.23.5.2814] Resolving...
[Version:1.12.2-forge1.12.2-14.23.5.2814] Inherits from 1.12.2
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1
flush now
flush now

What in the world happened here? It's suddenly become impossible to play with these mods loaded.

**Comment by coderbot16** [comment]
You need to update Traverse and Terrestria to the latest versions for 1.16.3. You have Terrestria 2.1.2 but need 2.1.4.

**Comment by apceros1** [comment]
Didn't think it was going to be that simple, thanks a bunch!

**Comment by coderbot16** [comment]
No problem!
