### ISSUE TITLE
Game Crash on startup

### ISSUE THREAD

**Issue by Tvpattack** [TerraformersMC/Terrestria#331]
Currently, it seems that terrestria is crashing a fabricmc instance I have on my personal computer that I've been trying to update to the latest version. Here's the most relevant error log that I saw, followed by the full error log:

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.terrestria-common.json:MixinFluidBlock from mod terrestria-common] from phase [DEFAULT] in config [mixins.terrestria-common.json] FAILED during APPLY

Full error log:
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-08-28 17:56:12
Description: Bootstrap

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2404 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:52)
	at net.minecraft.client.main.Main.main(Main.java:130)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.terrestria-common.json:MixinFluidBlock from mod terrestria-common] from phase [DEFAULT] in config [mixins.terrestria-common.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2404::terrestria$generateVolcanicCobblestone with priority 1000 cannot inject into net/minecraft/class_2404::method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z merged by niv.flowstone.mixin.LiquidBlockMixin with priority 1000 [INJECT_PREPARE Applicator Phase -> mixins.terrestria-common.json:MixinFluidBlock from mod terrestria-common -> Prepare Injections -> wrapOperation$ceo000$terrestria-common$terrestria$generateVolcanicCobblestone(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z -> Prepare ->  -> { target: method_10316(Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_2680;)Z }]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:312)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:248)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:475)
	at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.prepare(WrapOperationInjectionInfo.java:38)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1407)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:52)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24070.5 (e798126f926dd886b32c6c109a80cc3baf14090c):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		javaw.exe:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		jimage.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		jli.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		jna14252668423533699986.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		jvm.dll:Zulu 64-Bit Server VM:21.0.3:Azul Systems Inc.
		kernel.appcore.dll:AppModel API Host:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		management.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		management_ext.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		msvcp140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		nio.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.4111 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		verify.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
		win32u.dll:Win32u:10.0.22621.4111 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Zulu Platform x64 Architecture:21.0.3:Azul Systems Inc.
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:130)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 92272640 bytes (87 MiB) / 629145600 bytes (600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 30.0.101.1122
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 16669.63
	Virtual memory used (MiB): 9816.65
	Swap memory total (MiB): 8704.00
	Swap memory used (MiB): 430.23
	Space in storage for jna.tmpdir (MiB): available: 71529.52, total: 242921.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 71529.52, total: 242921.00
	Space in storage for io.netty.native.workdir (MiB): available: 71529.52, total: 242921.00
	Space in storage for java.io.tmpdir (MiB): available: 71529.52, total: 242921.00
	Space in storage for workdir (MiB): available: 71529.52, total: 242921.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		adaptiveview: AdaptiveView 2.3.0+1.21
		anvilrestoration: Anvil Restoration 2.3
		architectury: Architectury 13.0.6
		axesareweapons: Axes Are Weapons 1.9.1
		better_craftables: Better Craftables 2.0.0
		blockus: Blockus 2.9.2+1.21.1
			terraform-wood-api-v1: Terraform Wood API (v1) 11.0.0-alpha.1
		bottledair: Bottled Air 2.4
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		compostbag: CompostBag 4.1.0
		cooldown-coordinator: Cooldown Coordinator 0.8.0-beta.4
			mixinsquared: MixinSquared 0.2.0-beta.6
		copperhopper: Copper Hopper 0.9.3+1.21
		crockpot: Crock Pot 1.14.3+1.21
		deathbackup: Death Backup 3.4
		ductwork: Ductwork 0.9.1
		dynamic_asset_generator: Dynamic Asset Generator 6.1.1
		energizedpower: Energized Power 1.21-2.12.1-fabric
			team_reborn_energy: Energy 4.1.0
		evs: Enchanted Vertical Slabs 2.2
		excavated_variants: Excavated Variants 4.3.0
			defaultresources: Default Resources 3.6.0
		exlinefurniture: Exline's Furniture 1.0.7
		exotelcraft: Exotelcraft 6.0.0-ALPHA-3
		expandedstorage: Expanded Storage 14.1.3
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		flowstone: Flowstone 6.3+1.20.2
		guarding: Guarding 1.21.1-2.7.3
		healingcampfire: Healing Campfire 6.1
		highspeed-rail: High-Speed Rail 0.8.1+1.21
		improved_anvils: Improved Anvils 1.0.6-1.21
		indypets: IndyPets - Independent Pets 1.4.0
		java: OpenJDK 64-Bit Server VM 21
		jbr: Just Better Recipes 1.3.2
		lenientdeath: Lenient Death 1.2.5+1.21.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			jackfredlib-base: JackFredLib: Base 1.4.0+1.21
			jackfredlib-colour: JackFredLib: Colour 1.1.0+1.21
			jackfredlib-config: JackFredLib: Config 0.2.3+1.21
				blue_endless_jankson: jankson 1.2.3
				commons-io_commons-io: commons-io 2.15.1
			jackfredlib-lying: JackFredLib: Lying 0.5.5+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
				packet_tweaker: Packet Tweaker 0.5.1+24w03b
		loyal_items: Loyal Items 1.0.2
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moreberries: More Berries 1.5.11
		mr_aetherial_islands: Aetherial Islands 1-v1.0.3
		mr_better_sniffers: Better Sniffers 4.5
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.3
		mr_gardeners_dream: Gardener's Dream 1.5
		mr_ironfish: Ironfish 1-mcmeta-45_1.21
		mr_just_anotherstructurepack: Just Another Structure Pack 2.0
		mr_leather_bundles1: Leather Bundles 1.1
		mr_purpurpacks_irontodiamondarmorupgrades: Iron to Diamond Armor Upgrades [PurpurPack] 3.0
		mr_purpurpacks_irontodiamondtoolsupgrades: Iron to Diamond Tools Upgrades [PurpurPack] 3.0
		mr_purpurpacks_stonetoirontoolsupgrades: Stone to Iron Tools Upgrades [PurpurPack] 3.0
		mr_purpurpacks_woodentostonetoolsupgrades: Wooden to Stone Tools Upgrades [PurpurPack] 3.0
		mr_qraftys_bunkers: qrafty's Underground Villages 2.2
		mr_qraftys_oilrigs: qrafty's Oilrigs 2.2
		mr_revamped_floatingnether: Revamped Floating Nether 1-v1.1.1
		mr_serversleep: Server Sleep 1-datapack
		mr_soul_soilisdirt: Soul Soil is Dirt 1.0.0
		mr_stackable_items: Stackable Items 1.1.1
		mr_stonecutter_salvage: Stonecutter Salvage 1.0.0
		no_void_structures: No_void_structures 1.0.0
		nohostilesaroundcampfire: No Hostiles Around Campfire 7.1
		sketch: Sketch 1.21.1-1.2.1
		stackable: Stackable 1.2.2
		terrestria: Terrestria 7.0.0
			biolith: Biolith 3.0.0-alpha.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 11.0.0-alpha.1
			terraform-config-api-v1: Terraform Config API (v1) 11.0.0-alpha.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 11.0.0-alpha.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 11.0.0-alpha.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 11.0.0-alpha.1
			terraform-tree-api-v1: Terraform Tree API (v1) 11.0.0-alpha.1
			terrestria-client: Terrestria: Client 7.0.0
			terrestria-common: Terrestria: Common 7.0.0
			terrestria-worldgen: Terrestria: World Generation 7.0.0
		toms_storage: Tom's Simple Storage Mod 2.0.10
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-block: Cardinal Components API (blocks) 6.1.0
		traverse: Traverse 8.0.0
			traverse-client: Traverse: Client 8.0.0
			traverse-common: Traverse: Common 8.0.0
			traverse-worldgen: Traverse: World Generation 8.0.0
		treeharvester: Tree Harvester 9.1
		walk-jog-run: Walk, Jog, Run 1.1.0+1.21
		wheelbarrow: Wheelbarrow 1.0.2
		whereisit: Where Is It 2.5.0+1.21
			jackfredlib: JackFredLib 0.10.0+1.21
				jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.21
				jackfredlib-gps: JackFredLib: GPS 1.0.7+1.21
				jackfredlib-toasts: JackFredLib: Toasts 1.1.0+1.21
		wooltostring: Wool to String 1.0.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.21
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: ERR
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: <unknown>

**Comment by gniftygnome** [comment]
This looks like a mixin conflict between Terrestria and Flowstone.  It seems that Flowstone has added a bunch of features recently and one of them uses a non-compatible mixin.  I will probably have to discuss with Niv Oridocs; this might take a while.

**Comment by gniftygnome** [comment]
The crash should be resolved in Flowstone 6.4.  I think it must have also affected the Carpet mod.  ;)

However, this implementation will still break Terrestria's support for Volcanic Rock stone generators.  I'll try and work out a fix for that when I have some time.
